name: Docker Build and Push

on:
  push:
    branches: [ "master" ]  # 當推送到 main 分支時觸發
  pull_request:
    branches: [ "master" ]  # 當對 main 分支發起 PR 時觸發
  workflow_dispatch:  # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_NAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: WebAPI1
        file: WebAPI1/Dockerfile
        push: true
        tags: piau880906/backend:latest
